# -*- coding: utf-8 -*-
"""task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjWAeL_J81vcFk4N5-_Ntpyz2SFBNcJn
"""



"""
# **WAP to enter a number from user and print its absolute value.**"""

num=int(input("enter number "))
if num<0:
  abs=num*-1
  print(f"abs value = {abs}")
else:
  print(f"abs value = {num}")

"""# **WAP to enter a year from user and check if it is leap year or not.**"""

year = int(input("enter year: "))

if (year % 4 == 0 ):
    print(f"{year} is leap year")
else:
    print(f"{year} is not leap year")

"""# **WAP to enter the age of 3 person and print oldest and yougest among them.**"""

st_person=int(input("enter age of 1st person: "))
nd_person=int(input("enter age of 2nd person: "))
rd_person=int(input("enter age of 3rd person: "))

if st_person > nd_person and st_person > rd_person :
  print(f"\noldest age is {st_person}")

  if nd_person > rd_person :
      print(f"youngest age is {rd_person}")
  else:
      print(f"youngest age is {nd_person} ")


elif nd_person > st_person and nd_person > rd_person :
  print(f"\noldest age is {nd_person}")


  if st_person > rd_person :
    print(f"youngest age is {rd_person}")
  else:
    print(f"youngest age is {st_person}")


elif rd_person > st_person and rd_person > nd_person :
  print(f"\noldest age is {rd_person}")

  if st_person >nd_person :
    print(f"youngest age is {nd_person}")
  else:
    print(f"youngest age is {st_person}")

"""# **Write a program that asks the user to enter a series of numbers. The program should ask for numbers until the user enters a negative number. Once the user enters a negative number, the program should stop and print the sum of all the positive numbers entered**
# **Example**
# **Enter a number: 5**
# **Enter a number: 8**
# **Enter a number: 12**
# **Enter a number: -2**
# **The sum of the positive numbers is 25.**
"""

num=int(input("enter number: "))

sum=0
while num>=0:
  sum +=num
  num=int(input("enter number: "))

print(f"\nsum of the positive numbers is {sum}")

"""# **Write a program that asks the user to enter their name and age. The program should check if the user's age is greater than or equal to 18. If it is, the program should print a message saying they are eligible to vote. Otherwise, the program should print a message saying they are not eligible to vote due to being underage.**"""

name=input("enter name: ")
age=int(input("enter age: "))
if age>=18:
  print(f"{name} is eligible to vote")
else:
  print(f"{name} is not eligible to vote to being underage")

"""# **Write a Python Program to Find the Factorial of a Number**"""

num=int(input("enter number: "))
fact=1
while num>0:
  fact=fact*num
  num=num-1

print(f"factorial of num is {fact}")

